"use client"

import Providers from './Providers'
import ThemeButton from './components/ThemeButton'
import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link';
//import Header from './components/header';
import { usePathname } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {

  const currentRoute = usePathname();

  return (
    <html lang="en" className="dark" style={{ colorScheme: "dark" }}>
      <body className={inter.className}>
        <Providers>
        <header className="header">
          <nav className="nav-container">
            <ul className="list-container">
              <li>
                <Link 
                  href="/"
                  className={currentRoute === "/" ? "active-link" : "non-active-link"}  
                  >home</Link>
                <Link 
                  href="/about"
                  className={currentRoute === "/about" ? "active-link" : "non-active-link"}
                >about</Link>
                <Link 
                  href="/contact"
                  className={currentRoute === "/contact" ? "active-link" : "non-active-link"}
                >contact</Link>
              </li>
            </ul>
            <ThemeButton />
          </nav>
            
        </header>


          <main>{children}</main>
          <footer></footer>
        </Providers>
      </body>
    </html>
  )
}
